### PR TITLE
[QRF-350] Fix typo in Periodicity.BI_ANUALLY enum value

### PR DESCRIPTION
**Pull request by oleg-semyonov**

### CODE REVIEW

**Review by marko-ogg — APPROVED** [review]

**Review by e1himself — APPROVED** [review]
The change looks good. But I suspect you want it on the 7.x branch first, right?

**Comment by oleg-semyonov** [comment]
It looks like I'll need to create a new PR to merge into `7.x` branch, somehow Git doesn't want to rebase this branch on top of `7.x` 😕 

@e1himself how would you go about it? I'm not sure what's best:
a) Close this PR and create a new one to merge into `7.x,` then we will cherry-pick the commits into `master` branch
b) Merge this PR into `master` and create a new PR for `7.x` branch

**Comment by e1himself** [comment]
@oleg-semyonov 

c) Close this PR and create a new one to merge into 7.x. Then release 7.x.

I will propagate the changes to master by merging 7.x into 8.x and then into master.

**Comment by e1himself** [comment]
@oleg-semyonov Yes, please close this PR and create a new one to merge into 7.x. Then release 7.x.

> somehow Git doesn't want to rebase this branch on top of 7.x 

This is weird. It's the first time I see this behavior :man_shrugging:

**Pull request closed without merging**
