### PR TITLE
Feature - Type-hint Story `content` property

### PR DESCRIPTION
**Pull request by e1himself**
- Use `@prezly/slate-types` package to type hint v3 stories `content` prop

### CODE REVIEW

**Review by kamilmielnik — APPROVED** [review]

**Comment by kamilmielnik** [comment]
"Check / Build, Test & Prettier (10.x)" - that GitHub action does not like seem to like SRP :)

If all we get errors from test phase & prettier phase, will we see both errors at once, or do we have to fix the first one, run build again, and only then be able to see the second error?

**Comment by e1himself** [comment]
@kamilmielnik 

> "Check / Build, Test & Prettier (10.x)" - that GitHub action does not seem to like SRP :)

Indeed :)

> If we get errors from test phase & prettier phase, will we see both errors at once, or do we have to fix the first one, run build again, and only then be able to see the second error?

It stops on the first failed step:

https://github.com/prezly/javascript-sdk/blob/10e03e6b964a6981fdd8686031ab71bceab7baea/.github/workflows/nodejs.yml#L26-L36

This, however, can be changed to run them in parallel (see https://github.com/prezly/prezly/pull/9090 for example)

More importantly, I think you should look at this error:

> Error: node_modules/@prezly/slate-types/build/sdk/UploadcareFile.d.ts(1,26): error TS2307: Cannot find module 'uploadcare-widget' or its corresponding type declarations.

I guess this means that there is something wrong with the `@prezly/slate-types` package build.

**Comment by kamilmielnik** [comment]
Thanks, I'll have a look at it today!

**Comment by kamilmielnik** [comment]
I know what the problem is, but I still have to figure out the solution. I will continue tomorrow.

**Comment by kamilmielnik** [comment]
@e1himself fixed with https://github.com/prezly/javascript-sdk/pull/24/commits/c97a91d583d174dd6fae995f9301fe68fd19f7dc :construction_worker:

Thank you for the report!

**Comment by e1himself** [comment]
Thanks a lot for helping here @kamilmielnik :+1: :tada:

**Pull request merged**
